// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA26uMjGdj92x-e_PEyh7phQDB3rjBHfbU',
    appId: '1:119779839889:web:14baa254c4df2fcd645430',
    messagingSenderId: '119779839889',
    projectId: 'legalgene-dc6ed',
    authDomain: 'legalgene-dc6ed.firebaseapp.com',
    storageBucket: 'legalgene-dc6ed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAKtbUIj0BcECUhXpx_BEFMnu6DJE3Ptg',
    appId: '1:119779839889:android:912352ab093e4f59645430',
    messagingSenderId: '119779839889',
    projectId: 'legalgene-dc6ed',
    storageBucket: 'legalgene-dc6ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbvO8yFl8FmJwTTtjL2jYW7kLPSXulMX0',
    appId: '1:119779839889:ios:102e5528c5dfb131645430',
    messagingSenderId: '119779839889',
    projectId: 'legalgene-dc6ed',
    storageBucket: 'legalgene-dc6ed.appspot.com',
    iosBundleId: 'com.example.legalGene',
  );
}
